
services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: demo-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgvector-data-pg16:/var/lib/postgresql/data
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"

    volumes:
      - ollama:/root/.ollama

    restart: unless-stopped
  

volumes:
  pgvector-data-pg16:
    external: true
  ollama:
