spring.application.name=demo
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4.1-nano

spring.ai.model.embedding=openai
spring.ai.openai.embedding.options.model=text-embedding-3-small
spring.ai.ollama.embedding.enabled=false

spring.ai.mcp.server.protocol=STREAMABLE;
spring.ai.mcp.server.streamable-http.mcp-endpoint=/mcp

mcp.filesystem.root-dir=C:/lab/data
mcp.filesystem.max-fetch-bytes=200000
mcp.filesystem.max-search-results=50


spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.ai.vectorstore.pgvector.index-type=hnsw
spring.ai.vectorstore.pgvector.distance-type=cosine-distance
spring.ai.vectorstore.pgvector.dimensions=1536
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.max-document-batch-size=10000


spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2


spring.ai.openai.image.options.model=gpt-image-1.5

weather.api.key=${WEATHER_API_KEY}
weather.api.base-url=http://api.openweathermap.org/data/2.5/weather



spring.ai.mcp.client.toolcallback.enabled=false

notion.mcp.base-url=http://localhost:3000
notion.mcp.auth-token=${AUTH_TOKEN}